### ISSUE TITLE
Volume Averaging not in line with calibration routine or config description

### ISSUE THREAD

**Issue by shockerengr** [OSCSYS/brewtroller#1]
A volume read interval and count are defined in the BT configuration, when performing a calibration the system takes a reading, waits for the interval, takes an additional reading, and repeats until the defined number of readings is taken, then averages them for the calibration value.

During operation, the system takes the defined number of readings in quick succession, averages them for the current volume, then waits for the read interval before repeating.

This prevents the system from averaging longer time scale physical perturbations on the volume input, where the noise period is closer to 300ms (3 bubbles / sec).

System operation should be modified to follow calibration method where readings are spaced apart then averaged.

This may also necessitate changing the default interval to preserve and acceptable update rate.

**Comment by mattreba** [comment]
The volume logic take a sample at the VOLUME_READ_INTERVAL and averages the last VOLUME_READ_COUNT readings to come up with the new volume. This is the same thing that the calibration function does.

**Comment by mattreba** [comment]
void updateVols() {
  //Check volume on VOLUME_READ_INTERVAL and update vol with average of VOLUME_READ_COUNT readings
  if (millis() - lastVolChk > VOLUME_READ_INTERVAL) {
    for (byte i = VS_HLT; i <= VS_KETTLE; i++) {
      volReadings[i][volCount] = readVolume(vSensor[i], calibVols[i], calibVals[i]);
      unsigned long volAvgTemp = volReadings[i][0];
      for (byte j = 1; j < VOLUME_READ_COUNT; j++)
      volAvgTemp += volReadings[i][j];
      volAvg[i] = volAvgTemp / VOLUME_READ_COUNT; 
    }
    volCount++;
    if (volCount >= VOLUME_READ_COUNT) volCount = 0;
    lastVolChk = millis();
  }
}

**Comment by mattreba** [comment]
Notice the update only occurs if the VOLUME_READ_INTERVAL has been exceeded. Then it updates for each vessel. Only one reading takes place but the slot rotates on each update. Finally it averages the readings to determine the new rolling average.

**Comment by shockerengr** [comment]
that's what I get for reviewing code on breaks at work...

**Comment by mattreba** [comment]
The code should be written so it can be more easily followed.
