### ISSUE TITLE
PID still computing when RGBIO output is off or forced on

### ISSUE THREAD

**Issue by AllanMar** [OSCSYS/brewtroller#15]
This causes the PID to wind up. I will submit a bit of a hacky fix. There are a few problems with the way the current code is an transitioning from auto/manual. Until we have some sort of vessel class where PID operation can be more closely/consistently tied to everything else this will be a bit messy to handle IMHO.

**Comment by mattreba** [comment]
We could modify the analogoutput_SWPWM class to add an isEnabled() method
that would check if its pin index is enabled in the outputsystem
enablemask. Then in the vessel pid update if not isenabled()
pid.mode=MANUAL. Finally modify the compute call to only occur if AUTO.

**Comment by AllanMar** [comment]
Would isEnabled() also check if the output is forced on? or should we add a second method?
For a change I want to make for myself (my soft switch that enables/disables dual elements), it would be useful to have a method that returns RGBIO state.Which could be based upon output mask/enabled mask rather than RGBIO class.
It gets a bit more tricky to consider all the scenarios but we should also be updating the PIDOutput in some scenarios as the PID logic uses it for bumperless transfer from manual->auto (although i'm not sure we always want this).
pid.compute can always be called, the pid LIB will not compute it if mode is manual.

**Comment by mattreba** [comment]
Is the logic used to enable the second element consistent or just for
testing right now?

The isEnabled() and isForcedOn() would be used the same, right? Maybe just
a single method for isOverriden() or something like that.

Detecting the forced on is a bit trickier. Essentially it needs to ask "is
anyone other than me activating this output?" I don't want to limit the
logic to just the rgbio. I'd like to extend the rgbio type control to the
btnic logic. There's also a possibility of a trigger action that activates
an output.

We could add a method to outputsystem that does a getState with a profile
filter. The issue is that the swpwm uses the "discreet state" instead of
dedicating an output profile. That could be changed if needed.

**Comment by AllanMar** [comment]
My element logic (I haven't yet implemented in any form on this branch):
Theres 3 outputs. One enables HLT contactors, one enables dual elements and one enables BK contactors.

So if the element softswitch is HLT and HLT soft sw is Auto or ON, turn on the HLT contactor & dual element output.
If element softswitch is OFF and HLT is auto/on, turn HLT contactor on and so on.

So If I switch the element soft switch to BK, it will always disable the HLT contactors. enable the dual element output, and only enable the BK contactors if the BK soft switch is auto or on.

I couldn't figure out a clean way to implement this thats configurable (without a ton of changes) and i'm not sure it has many uses besides mine.

I'll have to have another look at ways to implement this in the scope of the original issue here.

**Comment by AllanMar** [comment]
Added OutputSystem::getOutputStatus(outputIndex) which returns the state of an output (Disabled/forced/AutoOn/AutoOff.
Have to implement this check in the PID logic (if status != disabled/forced then compute).

Right now getOutputStatus loops through the profiles. Not sure if it makes more sense to save the mask's required in update() and simply check them in getOutputStatus? as getOutputStatus could be called many times? Not sure if it a significant difference?
Let me know if this is along the lines of what you were thinking @mattreba

**Comment by AllanMar** [comment]
Almost there. Need to better address boil kettle manual %/transfer.
PID lib is meant to have bumper-less transfer which means we should set PIDOutput to max/min when forced on/off. Since we only save BK manual power in PIDOutput this overwrites the manual % when transitioning. 
I think were going to have to store manual boil power in it's own variable and use it to set PIDOutput based upon BK mode.

**Comment by mattreba** [comment]
Re: Loops through output profiles: This should not be too significant as all data is in RAM. Alternatively, you could calculate new bitmask variables disabledOutputs and forcedOutputs on outputSystem::update() and then just reference the masks form the respective per output calls. +8 bytes of RAM (insignificant) versus the loops.

So I did a sample sketch to gauge the impact of the profile loops:

```
void setup() {
  Serial.begin(115200);

  //Generate run-time data so compiler does not optimize our test
  unsigned long values[16];
  for (byte i = 0; i < 16; i++)
    values[i] = millis();

  {
    unsigned long result = 0;
    unsigned long timeStamp = millis();
    for (unsigned long j = 0; j < 1000; j++)
      for (byte i = 0; i < 16; i++)
        result |= values[i];
    timeStamp = millis() - timeStamp;
    char outputText[200];
    //Use the value or the compiler out smarts us
    Serial.println(result, DEC);
    sprintf(outputText, "16K OR ops took %ld ms", timeStamp);
    Serial.println(outputText);
  }
  {
    unsigned long result = 0xFFFFFFFFul;
    unsigned long timeStamp = millis();
    for (unsigned long j = 0; j < 1000; j++)
      for (byte i = 0; i < 16; i++)
        result &= values[i];
    timeStamp = millis() - timeStamp;
    char outputText[200];
    //Use the value or the compiler out smarts us
    Serial.println(result, DEC);
    sprintf(outputText, "16K AND ops took %ld ms", timeStamp);
    Serial.println(outputText);
  }
}

void loop() {}
```

And the result:

```
0
16K OR ops took 16 ms
0
16K AND ops took 17 ms
```

so about 1us per AND/OR operation. I would suggest this is also insignificant. It just comes down to what you prefer IMO.

**Comment by AllanMar** [comment]
I ended up moving it to the update loop in the latest commit. I didn't
think it would be significant but based upon how I was going to use it I
could see it being called multiple times. Made more sense to me given it
could be called multiple times, where as outputs->update can be controlled
how often it's called.
