### ISSUE TITLE
Volume Reading enhancement

### ISSUE THREAD

**Issue by shockerengr** [OSCSYS/brewtroller#2]
Current design for volume measurement converts each individual reading to a volume prior to averaging.  It would be more efficient to average the raw input readings first, then convert to volume measurement for system use.

**Comment by mattreba** [comment]
How would the proposed logic be more efficient? It's still going to need perform the ADC reading to calibrated volume conversion on each update. The only difference is averaging 16-bit ints verses 32-bit  longs. I'm not sure how much difference it makes.

**Comment by shockerengr** [comment]
it's a single lookup and conversion from the raw value to volume instead of for each individual reading.

this section of code when then be run a single time for each averaging rather than for each individual reading:

  byte upperCal = 0;
  byte lowerCal = 0;
  byte lowerCal2 = 0;
  for (byte i = 0; i < 10; i++) {
    #ifdef DEBUG_VOL_READ
      logFieldI(calibrationValues[i]);
    #endif
    if (aValue == calibrationValues[i]) { 
      upperCal = i;
      lowerCal = i;
      lowerCal2 = i;
      break;
    } else if (aValue > calibrationValues[i]) {
        if (aValue < calibrationValues[lowerCal]) lowerCal = i;
        else if (calibrationValues[i] > calibrationValues[lowerCal]) { 
          if (aValue < calibrationValues[lowerCal2] || calibrationValues[lowerCal] > calibrationValues[lowerCal2]) lowerCal2 = lowerCal;
          lowerCal = i; 
        } else if (aValue < calibrationValues[lowerCal2] || calibrationValues[i] > calibrationValues[lowerCal2]) lowerCal2 = i;
    } else if (aValue < calibrationValues[i]) {
      if (aValue > calibrationValues[upperCal]) upperCal = i;
      else if (calibrationValues[i] < calibrationValues[upperCal]) upperCal = i;
    }
  }
  
  #ifdef DEBUG_VOL_READ
    logFieldI(upperCal);
    logFieldI(calibrationVols[upperCal]);
    logFieldI(lowerCal);
    logFieldI(calibrationVols[lowerCal]);
    logFieldI(lowerCal2);
    logFieldI(calibrationVols[lowerCal2]);
  #endif
  
  //If no calibrations exist return zero
  if (calibrationValues[upperCal] == 0 && calibrationValues[lowerCal] == 0) retValue = 0;

  //If the value matches a calibration point return that value
  else if (aValue == calibrationValues[lowerCal]) retValue = calibrationVols[lowerCal];
  else if (aValue == calibrationValues[upperCal]) retValue = calibrationVols[upperCal];
  
  //If read value is greater than all calibrations plot value based on two closest lesser values
  else if (aValue > calibrationValues[upperCal] && calibrationValues[lowerCal] > calibrationValues[lowerCal2]) retValue = round((float) ((float)aValue - (float)calibrationValues[lowerCal]) / (float) ((float)calibrationValues[lowerCal] - (float)calibrationValues[lowerCal2]) * ((float)calibrationVols[lowerCal] - (float)calibrationVols[lowerCal2])) + calibrationVols[lowerCal];
  
  //If read value exceeds all calibrations and only one lower calibration point is available plot value based on zero and closest lesser value
  else if (aValue > calibrationValues[upperCal]) retValue = round((float) ((float)aValue - (float)calibrationValues[lowerCal]) / (float) ((float)calibrationValues[lowerCal]) * (float)((float)calibrationVols[lowerCal])) + calibrationVols[lowerCal];
  
  //If read value is less than all calibrations plot value between zero and closest greater value
  else if (aValue < calibrationValues[lowerCal]) retValue = round((float) aValue / (float) calibrationValues[upperCal] * (float)calibrationVols[upperCal]);
  
  //Otherwise plot value between lower and greater calibrations
  else retValue = round((float) ((float)aValue - (float)calibrationValues[lowerCal]) / (float) ((float)calibrationValues[upperCal] - (float)calibrationValues[lowerCal]) * ((float)calibrationVols[upperCal] - (float)calibrationVols[lowerCal])) + calibrationVols[lowerCal];

  #ifdef DEBUG_VOL_READ
    logFieldI(retValue);
    logEnd();
  #endif
  return retValue;

**Comment by shockerengr** [comment]
nm

**Comment by mattreba** [comment]
The more I think about it the more your changes make sense. It would cut the memory usage by half and the averaging would have to be a few cycles less for 16-bit vs 32-bit values i'd assume.
