### ISSUE TITLE
ON/OFF heat control

### ISSUE THREAD

**Issue by Asbjoern** [OSCSYS/brewtroller#31]
You should consider re-implementing on/off heat control option. PWM output is not really good when using gas heaters.
You can properbly hack it in by setting the K constant way high (To always give full control signal) and the I & P constant to zero (Remove time component). 
Or maybe set the PWM Res to 1?

Burn time based PID istead of PWM would be ideal and will still work for electric heaters.

**Comment by mattreba** [comment]
On/off heat control is still supported. Each vessel has a Heat, and Idle
output profiles in addition to the PWM Output and PWM Active Output
profile. Heat/Idle is based on hysteresis setting for vessel. PWM logic and
ON/OFF control are always enabled you simply do not configure outputs for a
mode you are not using.

**Comment by Asbjoern** [comment]
Yes of course ON/OFF heater is just another output. 
Thank you!
