### ISSUE TITLE
Move libraries into code base

### ISSUE THREAD

**Issue by mattreba** [OSCSYS/brewtroller#6]
Eliminate dependencies on a customized Arduino by eliminating external libraries. Instead include libraries in the source directly. This will also enable changes to libraries more easily without requiring the user to download a new custom Arduino IDE. Some customization of Arduino will still be needed to support the ATMEGA1284P.

**Comment by AllanMar** [comment]
This should be completed as of c95eeadddf0d4f8399a5acde5687b5a89e1acede ?
